package com.ngshah.devicetracker.utils;

public class Common {
	
	public static String[] prefixes = {"IMEI", "IMSI", "IMEIIMSI", "IMEI IMSI",
		"CELLLOCATION", "CELL LOCATION", "CELL INFO", "CELLINFO",
		"LOCATION", "GPS LOCATION", "GPS",
		"CLEAR DATA", "CLEARDATA", "WIPE DEVICE", "WIPEDEVICE", "WIPEDATA", "WIPE DATA",
		"RING", "VIBRATE", "RING AND VIBRATE", "RINGANDVIBRATE",
		"LOCK DEVICE", "LOCKDEVICE", "SCREEN LOCK", "SCREENLOCK",		//	24
		"ENABLE APPLICATION", "ENABLEAPPLICATION", "ENABLE LAUNCHER", "ENABLELAUNCHER",		//	28
		"DISABLE APPLICATION", "DISABLEAPPLICATION", "DISABLE LAUNCHER", "DISABLELAUNCHER",		//	32
		};
}